"""initial slice-1 schema (sl_ prefixed)

Revision ID: b7b3d6ea0213
Revises:
Create Date: 2026-07-24 22:15:24.933419
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b7b3d6ea0213"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sl_songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=260), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sl_songs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sl_songs_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_sl_songs_title"), ["title"], unique=False)

    op.create_table(
        "sl_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("handle", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sl_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sl_users_handle"), ["handle"], unique=True)

    op.create_table(
        "sl_artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sl_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sl_artists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sl_artists_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sl_artists_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_sl_artists_slug"), ["slug"], unique=True)

    op.create_table(
        "sl_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column("resolver_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["sl_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolver_id"],
            ["sl_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sl_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sl_reports_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sl_reports_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sl_reports_status"), ["status"], unique=False)

    op.create_table(
        "sl_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=280), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["sl_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sl_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sl_revisions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sl_revisions_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sl_revisions_entity_type"), ["entity_type"], unique=False
        )

    op.create_table(
        "sl_performances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["sl_artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sl_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artist_id", "venue", "performed_on", name="uq_perf_artist_venue_date"),
    )
    with op.batch_alter_table("sl_performances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sl_performances_artist_id"), ["artist_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sl_performances_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sl_performances_performed_on"), ["performed_on"], unique=False
        )

    op.create_table(
        "sl_attendances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["sl_performances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sl_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "user_id", name="uq_attendance_once"),
    )
    with op.batch_alter_table("sl_attendances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sl_attendances_performance_id"), ["performance_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sl_attendances_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sl_setlist_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sl_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["sl_performances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["sl_songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "position", name="uq_setlist_perf_position"),
    )
    with op.batch_alter_table("sl_setlist_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sl_setlist_entries_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sl_setlist_entries_performance_id"), ["performance_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sl_setlist_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_setlist_entries_performance_id"))
        batch_op.drop_index(batch_op.f("ix_sl_setlist_entries_is_archived"))

    op.drop_table("sl_setlist_entries")
    with op.batch_alter_table("sl_attendances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_attendances_user_id"))
        batch_op.drop_index(batch_op.f("ix_sl_attendances_performance_id"))

    op.drop_table("sl_attendances")
    with op.batch_alter_table("sl_performances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_performances_performed_on"))
        batch_op.drop_index(batch_op.f("ix_sl_performances_is_archived"))
        batch_op.drop_index(batch_op.f("ix_sl_performances_artist_id"))

    op.drop_table("sl_performances")
    with op.batch_alter_table("sl_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_revisions_entity_type"))
        batch_op.drop_index(batch_op.f("ix_sl_revisions_entity_id"))
        batch_op.drop_index(batch_op.f("ix_sl_revisions_created_at"))

    op.drop_table("sl_revisions")
    with op.batch_alter_table("sl_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_reports_status"))
        batch_op.drop_index(batch_op.f("ix_sl_reports_entity_type"))
        batch_op.drop_index(batch_op.f("ix_sl_reports_entity_id"))

    op.drop_table("sl_reports")
    with op.batch_alter_table("sl_artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_artists_slug"))
        batch_op.drop_index(batch_op.f("ix_sl_artists_name"))
        batch_op.drop_index(batch_op.f("ix_sl_artists_is_archived"))

    op.drop_table("sl_artists")
    with op.batch_alter_table("sl_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_users_handle"))

    op.drop_table("sl_users")
    with op.batch_alter_table("sl_songs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sl_songs_title"))
        batch_op.drop_index(batch_op.f("ix_sl_songs_slug"))

    op.drop_table("sl_songs")
    # ### end Alembic commands ###
