"""initial schema

Revision ID: e2e97c4120f7
Revises:
Create Date: 2026-07-24 14:54:24.242707
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e2e97c4120f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=260), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_songs_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_songs_title"), ["title"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("handle", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_handle"), ["handle"], unique=True)

    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artists_is_archived"), ["is_archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_artists_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_artists_slug"), ["slug"], unique=True)

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column("resolver_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolver_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_entity_type"), ["entity_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_status"), ["status"], unique=False)

    op.create_table(
        "revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=280), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_revisions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_revisions_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_revisions_entity_type"), ["entity_type"], unique=False)

    op.create_table(
        "performances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artist_id", "venue", "performed_on", name="uq_perf_artist_venue_date"),
    )
    with op.batch_alter_table("performances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performances_artist_id"), ["artist_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_performances_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_performances_performed_on"), ["performed_on"], unique=False
        )

    op.create_table(
        "attendances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["performances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "user_id", name="uq_attendance_once"),
    )
    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendances_performance_id"), ["performance_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attendances_user_id"), ["user_id"], unique=False)

    op.create_table(
        "setlist_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["performances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "position", name="uq_setlist_perf_position"),
    )
    with op.batch_alter_table("setlist_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_setlist_entries_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_setlist_entries_performance_id"), ["performance_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("setlist_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setlist_entries_performance_id"))
        batch_op.drop_index(batch_op.f("ix_setlist_entries_is_archived"))

    op.drop_table("setlist_entries")
    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendances_user_id"))
        batch_op.drop_index(batch_op.f("ix_attendances_performance_id"))

    op.drop_table("attendances")
    with op.batch_alter_table("performances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performances_performed_on"))
        batch_op.drop_index(batch_op.f("ix_performances_is_archived"))
        batch_op.drop_index(batch_op.f("ix_performances_artist_id"))

    op.drop_table("performances")
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revisions_entity_type"))
        batch_op.drop_index(batch_op.f("ix_revisions_entity_id"))
        batch_op.drop_index(batch_op.f("ix_revisions_created_at"))

    op.drop_table("revisions")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_status"))
        batch_op.drop_index(batch_op.f("ix_reports_entity_type"))
        batch_op.drop_index(batch_op.f("ix_reports_entity_id"))

    op.drop_table("reports")
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artists_slug"))
        batch_op.drop_index(batch_op.f("ix_artists_name"))
        batch_op.drop_index(batch_op.f("ix_artists_is_archived"))

    op.drop_table("artists")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_handle"))

    op.drop_table("users")
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_songs_title"))
        batch_op.drop_index(batch_op.f("ix_songs_slug"))

    op.drop_table("songs")
    # ### end Alembic commands ###
